autotest/autotest-client-tests

linux-tools/python_match_hostname/control, linux-tools/python_match_hostname/python_match_hostname.py
Secure Socket Layer is secure when the hostname in the certificate returned
by the server matches to hostname thats being trying to be reached.
match_hostname() in ssl package in the Standard Library of Python 3.2 performs this check
instead of requiring every application to implement the check separately.
backport brings match_hostname() to users of earlier versions of Python.
Signed-off-by: Athira Rajeev<atrajeev@linux.vnet.ibm.com>
=> Testcase for python-backports-ssl_match_hostname

linux-tools/libteam/control, linux-tools/libteam/libteam.py
libteam - Library for controlling team network device
The purpose of the Team driver is to provide a mechanism to team multiple NICs (ports) into one logical one (teamdev) at L2 layer.
The process is called "channel bonding", "Ethernet bonding", "channel teaming", "link aggregation", etc.
This is already implemented in the Linux kernel by the bonding driver. libteam solve the same problem using a different approach
Signed-off-by: Athira Rajeev<atrajeev@linux.vnet.ibm.com>
=> Testcase for libteam

linux-tools/avahi_autoipd/avahi_autoipd.py, linux-tools/avahi_autoipd/control
avahi-autoipd - IPv4LL network address configuration daemon
avahi-autoipd implements IPv4LL, "Dynamic Configuration of IPv4 Link-Local Addresses" (IETF RFC3927), a protocol for automatic IP address configuration from the link-local 169.254.0.0/16 range without the need for a central server. It is primarily intended to be used in ad-hoc networks which lack a DHCP server
The package provides avahi-autoipd binary
Signed-off-by: Athira Rajeev<atrajeev@linux.vnet.ibm.com>
=> Testcase for avahi-autoipd

scsi_testsuite/fix_illegal_request_testing.patch
In these two case the scsi command result is invalid, so we probably
should only compare the sense data.
**NOTE**: this patch works for current RHEL.7 distibusion, where the version of command `sg_raw` is `0.4.6`.
ID: 1168787
=> scsi_testsuite: add patch for cases 005 and 006 to drop the comparison of received data

.travis.yml, requirements-selftests.txt
For some reason, the Travis environment doesn't set AUTOTEST_TOP_PATH
as one of the environment variables, making the setup script to
try to create /etc/autotest, causing the install to fail. Let's set
that variable and also adjust the requirements file to make the test
to go on.
Signed-off-by: Lucas Meneghel Rodrigues <lmr@scylladb.com>
=> Travis CI build fix

hackbench/hackbench.py
In gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, the -lpthread does not work if used before the 'hackbench.c'. It mus be in the end, right after '-o hackbench'
Signed-off-by: Victor Aoqui (@aoqui)
=> Fixed order of -lpthread parameter

linux-tools/busybox/busybox.sh, linux-tools/checkpolicy/sedispol.exp, linux-tools/dbus_python/dbus-python.sh, linux-tools/libedit/libedit_test.sh, linux-tools/libndp/control, linux-tools/libqb/libqb.sh, linux-tools/libteam/control, linux-tools/mcelog/mcelog.py, linux-tools/numactl/numactl.sh, linux-tools/openslp/openslp.py, linux-tools/openssl/openssl.py, linux-tools/perl_XML_Simple/perl-XML-Simple.sh, linux-tools/policycoreutils/policycoreutils.sh, linux-tools/python_ldap/python_ldap.py, linux-tools/python_urlgrabber/python_urlgrabber.py
Busybox : The test chpasswd  were failing because of some messages in stderr,so handled it in wrapper script to ignore it.
Checkpolicy : modified sedispol.exp with correct pattern in expect script .
dbus_python : copied the test directory  to tmp and changed wrapper to run from /tmp to avoid error while starting the dbus-daemon (if path length is greater than  99 in dbus.conf <listen> field,the daemon will fail to start)
libndp/libteam: updated the test path in control file
libqb : Introduced sleep of 2 seconds between server and client connection.
perl_XML_Simple: commented out LTPBIN variable .
policycoreutils/python_ldap/python_urlgrabber/mcelog : modified .py file to apply existing patch in test folder .
openslp : corrected typo in .py file …
=> Linux_tools: Fixes for Integration bugs

linux-tools/pexpect_test/pexpect_test.py
Incorporated the changes suggested in pull request #87
pexpect_test : one of the test patch(pexpect-pxssh-scripts.diff) was not applied,due to which tests were failing ,hence made changes in pexpect_test.py to apply patch before triggering the tests.
Signed-off-by:ramyabsramya@linux.vnet.ibm.com
Tested-by:ramyabswramya@linux.vnet.ibm.com
=> Fixed pexpect_test to apply patch for the tests to run successfully

linux-tools/gpgme_test/gpgme.sh, linux-tools/pango/pango.sh
gpgme_test/pango : Fixed in .sh wrapper script(as we had used variable in sed command ,but it was not handled  properly,hence the wrong path was updated in respective files )
Signed-off-by:ramyabs<ramya@linux.vnet.ibm.com>
=> Fix for gpgme and pango shell wrapper script to handle test path correctly .

linux-tools/acpid/conf/rule1, linux-tools/acpid/conf/rule2, linux-tools/acpid/conf/rule3
acpid rules files were missing in conf directory, hence acpid failed to load rules while starting the acpid daemon. Adding these rule files addresses the issue.
=> Fixing acpid tests failure by adding the missing rule files in conf directory of acpid

linux-tools/policycoreutils/policycoreutils.sh
Problem Description :
After Disabling the module using semodule -d,the script was trying to grep the disabled module using command  semodule -l ,which was not throwing any output to stdout hence the test failed .
Fix :
changing  semodule -l to  semodule -list=full which will list the disabled modules on stdout and made grep command  more generic .
Signed-off-by: Ramya BS<ramyabs1@in.ibm.com>
=> Fix for policycoreutils-semodule:disable tests.

linux-tools/libnl/libnl.sh
The package libnl3-cli is providing some of the binaries(nl-link-stats ,nl-list-sockets etc )
as part of libnl3-cli package(system installed) ,earlier it was part of tests in source
This binaries which are coming as part of package libnl3-cli differs in some of the option when compare
to binaries present in test source ,so changed our wrapper to work accordingly with the installed binaries .
Signed-off-by: Ramya BSramyabs1@in.ibm.com
=> Fix for libnl.sh wrapper script to incorporate the latest changes made in the binaries .

linux-tools/audit/audit.sh
audit/audit.sh : Updated the kernel related configuration check for audit and test cleanup to restore the orginal.
Signed-off By: Anup Kumar <anupkumk@linux.vnet.ibm.com>
=> Fix for audit configuration issue on s390x arch.

.travis.yml
Recent versions of sphinx require setuptools, let's add
them to the .travis.yml file.
This should fix a CI problem in autotest-client-tests.
Signed-off-by: Lucas Meneghel Rodrigues <lookkas@gmail.com>
=> .travis.yml: Install setuptools before sphinx

linux-tools/pixman/pixman.sh
Updated the wrapper-script to filter out the affine-bench test,
since benchmarking tests are not used for functional testing.
Signed-off-by: Rajashree Rajendran <rajashre@linux.vnet.ibm.com>
=> pixman : Fix for affine-bench test

aio_dio_bugs/aio_dio_bugs.py, aio_dio_bugs/src/Makefile, aio_dio_bugs/src/aio-cve-2016-10044.c
This test will check if AIO memory mappings is executable for CVE-2016-10044,
code taken from the commit message in the patch for that CVE (22f6b4d3).
Original author: Jann Horn <jann@thejh.net>
Changed by Po-Hsu Lin to add it into the autotest framework.
Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>
=> aio_dio_bugs: add test case for CVE-2016-10044

aio_dio_bugs/src/aio-cve-2016-10044.c
It was found that this test case will not work as expected on i386 systems.
Which will print something like:
Permission for /[aio] is rw-s/[aio], expecting rw-s
FAILED. Vulnerable to CVE-2016-10044
This issue was caused by the insufficient size of the char array and the size
difference of a long integer on 32/64 bits system. Fix it by increasing the
array size and use inttypes.h to secure the variable size.
Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>
=> aio_dio_bugs: fix string overflow for aio-cve-2017-10044

rtc/src/rtctest.c
The power8 ppc64 machine does not support alarm interrupts and it
reports EINVAL, resp EIO on the RTC_UIE_ON, resp RTC_AIE_ON ioctls.
Let's skip to next test in such case.
Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>
=> rtc: Adjust the rtctest to work on ppc64

.travis.yml
It's the last one that actually works on python 2.6, so
let's pin that version down.
Signed-off-by: Lucas Meneghel Rodrigues <lookkas@gmail.com>
=> .travis.yml: Pin Sphinx version on 1.4.9

tsc/src/checktsc.c
Add some inline assembly code to read the CPU time counters on these
architectures, so that the test can be compiled and run here, too.
=> Fix the tsc test to also run on PPC64 and s390x

hwclock/hwclock.py
On some system, a HP ProLiant m400 Server in my case, this hwclock --set
operation will take about 0.5 - 1 second to finish. So if we fork another
subprocess immediately to check the output from hwclock, it will get the
timestamp before this modification.
Use utils.system_output() to wait for the hwclock --set command to finish.
Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>
=> hwclock: check the hwclock until --set operation finishes

rtc/src/rtctest.c
The rtc chip defined in qemu guest on ppc64 does not support alarms at
all, therefor RTC_ALM_READ fails with EINVAL. Let's proceed to next test
in such case.
@KarMez-Redhat, @clebergnu this addresses the in-guest issue with rtctest.
=> rtc: Also treat RTC_ALM_READ in rtctest on ppc64

linux-tools/pam_krb5/pam_krb5.py, linux-tools/pam_krb5/pam_krb5.sh
Issue 1: From the analysis, Tests in pam_krb5 needs tools/pam_harness.c file to be compiled to generate pam_harness binary which requires pam-devel package to be installed. so added a check and installation for pam-devel in python wrapper.
Issue 2: From the analysis, the issue raises with error Server not found in Kerberos database(KDC).
All Kerberos server machines uses credential cache (or “ccache”)  that holds Kerberos credentials or  keytab file (by default /etc/krb5.keytab) which contains key value pairs for authentication purpose.
Here in the test_password test it looks for the default keytab file (/etc/krb5.keytab) to get TGT (ticket to access the service) and the test fails with "server not found in kerberos database(KDC).
Since the kerberos is configured to use the temporary …
=> [PATCH] Fix for pam_krb5 authentication and make failure

linux-tools/libnfsidmap/libnfsidmap.sh
nfs-secure-server service is removed from nfs-utils RPM.
So remove this from testcase as well. Tests/functionality works fine with this change.
Signed-off-by: Athira Rajeev <atrajeev@linux.vnet.ibm.com>
=> libnfsidmap: Fix the testcase to remove nfs-secure-server

aio_dio_bugs/aio_dio_bugs.py, aio_dio_bugs/src/Makefile, aio_dio_bugs/src/aio-completions-lp-1641129.c
BugLink: https://bugs.launchpad.net/bugs/1641129
Add a regression test case for aio completion test.
Test case from http://www.kvack.org/~bcrl/20140824-aio_bug.c
This issue was introduced by:
f8567a3845ac05bb28f3c1b478ef752762bd39ef
And fixed by:
d856f32a86b2b015ab180ab7a55e455ed8d3ccc5
Signed-off-by: Po-Hsu Lin \<po-hsu.lin@canonical.com\>
=> aio_dio_bugs: add regression test for aio completion test
